### PR TITLE
Add initial testing values 

### PR DESCRIPTION
**Pull request by stan-dot**

### CODE REVIEW

**Comment by stan-dot** [comment]
consider a Dockerfile too?


```Dockerfile

FROM eclipse-temurin:17-jdk

RUN apt-get update && \
    apt-get install -y maven git && \
    apt-get clean

WORKDIR /workspace
COPY . /workspace

RUN mvn clean install


CMD ["java", "-jar", "target/ChannelFinder-*.jar", "--spring.config.name=application"]

```

**Comment by jacomago** [comment]
The docker container is already published on github https://github.com/ChannelFinder/ChannelFinderService/pkgs/container/channelfinderservice

**Comment by stan-dot** [comment]
ok I'll try with that one!

**Comment by stan-dot** [comment]
closing in favour of a different source https://github.com/DiamondLightSource/kubernetes

**Pull request closed without merging**
